server:
  port: 8080
  tomcat:
      uri-encoding: utf-8
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: tomcat

spring:
    datasource:
        name: mybatis_test
        #使用druid连接池
        type: com.alibaba.druid.pool.DruidDataSource
        mysql-8.0.12:
          driver-class-name: com.mysql.cj.jdbc.Driver
          #配置基本属性
          url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
          username: root
          password: 3828528

        mysql-5.7.17:
           url: jdbc:mysql://10.1.0.121:3306/test?allowMultiQueries=true&autoReconnect=true&useSSL=false
           username: root
           password: 1qaz2wsx
        #druid相关配置
        druid:
          #监控统计拦截的filters
#          filters: stat
          web-stat-filter:
              exclusions: \*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
          stat-view-servlet:
              login-username: druid
              ogin-password: druid
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 5
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
    profiles:
      active: dev
#邮件参数配置
email:
  #服务器
  host: smtp.partner.outlook.cn
  #端口号
  port: 587
  #邮箱账号
  username: admin
  #邮箱授权码
  password: admin
  #时间延迟
  timeout: 25000
  #发送者
  from: admin
  #系统名称
  personal: 黑客1号

